Set packpath in runtimedir
This way it's *before* everything else, which mimics how Vim behaves.
Otherwise it would load syntax/go.vim from the Go installation, rather
than the plugin's.

diff --git a/test-syntax b/test-syntax
--- a/test-syntax
+++ b/test-syntax
@@ -15,15 +15,19 @@ if [ $(link_pack "$@") -gt 0 ]; then
 	exit 2
 fi
 
+packdir="$tmpdir/pack/t/start/$(ls "$tmpdir/pack/t/start")"
 for f in "$@"; do
 	${TEST_VIM:-vim} --noplugin -u NONE -N -e \
-		+"set shm+=WAFI rtp^=$testingdir packpath=$tmpdir" \
+		+"set shm+=WAFI rtp^=$packdir packpath=$tmpdir" \
 		+'filetype plugin indent on' \
 		+'packloadall!' \
 		+"silent e $f" \
 		+"let g:test_tmpdir='$tmpdir'" \
 		-S "$testingdir/syntax.vim" \
-		-S "$testingdir/syntaxtest.vim" >/dev/null </dev/null
+		-S "$testingdir/syntaxtest.vim" >/dev/null </dev/null || (
+			echo  'TEST RUNNER FAILURE; error in syntaxtest.vim'
+			exit 5
+		)
 done
 
 printf '" This file is automatically generated by test-syntax from testing.vim'
